name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - uses: ./
        with:
          version-regexp: '\d'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
